; This file was auto-generated by drush make
core = 7.x

api = 2
projects[drupal][version] = ""

; Modules
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
projects[libraries][version] = ""
projects[navbar][version] = ""


; backbone
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[backbone][download][type] = "file"
libraries[backbone][download][url] = "http://backbonejs.org/backbone-min.js"
libraries[backbone][directory_name] = "backbone"
libraries[backbone][type] = "library"

; underscore
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[underscore][download][type] = "git"
libraries[underscore][download][url] = "https://github.com/jashkenas/underscore.git"
libraries[underscore][directory_name] = "underscore"
libraries[underscore][type] = "library"

; modernizr
; Please fill the following out. Type may be one of get, git, bzr or svn,
; and url is the url of the download.
libraries[modernizr][download][type] = "file"
libraries[modernizr][download][url] = "http://modernizr.com/downloads/modernizr-latest.js"
libraries[modernizr][download][filename] = "modernizr.js"
libraries[modernizr][directory_name] = "modernizr"
libraries[modernizr][type] = "library"
